apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tyk-gateway
  namespace: tyk
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 30s}
  selector:
    matchLabels:
      app: tyk-gateway
  template:
    metadata:
      labels:
        app: tyk-gateway
    spec:
      containers:
        - name: tyk-gateway
          image: tykio/tyk-gateway:v5.8.2
          ports:
            - containerPort: 8080
          extraEnvs:
            - name: TYK_GW_STORAGE_TYPE
              value: redis
            - name: global.redis.addrs
              value: tyk-redis-master.tyk.svc.cluster.local:6379
            - name: TYK_GW_STORAGE_ENABLECLUSTER
              value: "false"
            - name: TYK_GW_STORAGE_DATABASE
              value: "0"
            - name: TYK_GW_STORAGE_PASSWORD
              value: xymjss3MSd