apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tyk-gateway-rollout
  namespace: tyk
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 50
        - pause: { duration: 2m }
        - setWeight: 100
  selector:
    matchLabels:
      app: tyk-gateway
  template:
    metadata:
      labels:
        app: tyk-gateway
    spec:
      containers:
        - name: tyk-gateway
          image: tykio/tyk-gateway:v5.3.1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: tyk-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
